### ISSUE TITLE
Move params logic to hiera data

### ISSUE THREAD

**Issue by nward** [djjudas21/puppet-freeradius#162]
The puppet language style guide (https://puppet.com/docs/puppet/7.6/style_guide.html) recommends using data binding rather than the params.pp pattern.

As well as being a more "modern" way of doing things, this also allows the user to override anything that params.pp would currently be calculating - making the module a lot more flexible.

This has the negative impact that the module's supported minimum Puppet version would be 4.9, as this is when Hiera 5 with in-module hiera data support was added. Given this was released in 2017 I think this is an OK minimum version.

The current minimum version is 4.0.0 (2015).

An example of this would be:
`hiera.yaml`:
```yaml
---
version: 5

defaults:
  datadir: data
  data_hash: yaml_data

hierarchy:
  - name: "osfamily+osname/major release"
    paths:
      - "os/%{facts.os.name}/%{facts.os.release.major}.yaml"
      - "os/%{facts.os.family}/%{facts.os.release.major}.yaml"
  - name: "osfamily+osname"
    paths:
      - "os/%{facts.os.name}.yaml"
      - "os/%{facts.os.family}.yaml"
  - name: 'common'
    path: 'common.yaml'
```

`data/debian/9.yaml`:
```yaml
---
freeradius::package: freeradius
freeradius::raddbdir: '${sysconfdir}/freeradius/3.0'
#... etc ...
```

It would also mean making most (if not all) of the `fr_*` variables be straight params on the `freeradius` class, i.e., for the above examples:
```puppet
class freeradius (
  String $package,
  String $raddbdir,
#  .. etc ..
) {
# .. code ..
}
```
